services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: onlydevs_web
  
  clickhouse:
    restart: always
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native interface
    environment:
      - CLICKHOUSE_DB=onlydevs_lrs
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_USER=username
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    restart: always
    build:
      context: packages/lrs
      dockerfile: Dockerfile
      args:
        - APP_PATH=.
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
    depends_on:
      clickhouse:
        condition: service_healthy

  web:
    restart: always
    build:
      context: .
      dockerfile: packages/web/Dockerfile
    ports:
      - "3000:4321"
    depends_on:
      - db
      - backend
    environment:
      HOST: 0.0.0.0
      PORT: 4321
      KRATOS_URL: http://127.0.0.1:4433
      XAPI_SERVICE_URL: http://backend:8080
      PUBLIC_XAPI_SERVICE_URL: http://backend:8080
      WEB_DB: postgres://postgres:password@127.0.0.1:5432/onlydevs_web
      DATABASE_URL: postgresql://postgres:password@db:5432/onlydevs_web

  
