@startuml ERD

!define table(x) class x << (T,#FFAAAA) >>
!define primary_key(x) <b>x</b>
!define foreign_key(x) <u>x</u>

table(user) {
    primary_key(id): UUID
    email: TEXT
    username: TEXT
    password_hash: TEXT
    first_name: TEXT
    last_name: TEXT
    uco: TEXT
}

table(session) {
    primary_key(id): UUID
    foreign_key(user_id): TEXT
    expires_at: TIMESTAMP
}

table(student_lecture_status) {
    primary_key(id): UUID
    created_at: TIMESTAMP
    updated_at: TIMESTAMP
    email: VARCHAR(256)
    course: VARCHAR(256)
    lecture: VARCHAR(256)
    status: ENUM[inProgress, completed]
}

session }--|| user : belongs to
@enduml
